### ISSUE TITLE
Enabling emoji changes the behavior of the language switch button

### ISSUE THREAD

**Issue by nesnera** [maliit/keyboard#47]
Try to enable e.g. Czech, English and Emoji. Then activate Emoji in the virtual keyboard.
Use (tap) the button/key to select the language - the language does not switch, the icons are displayed. (Hold works properly 👍) 
I think emoji should be controlled separately.🤔

Linux plasma-mobile 5.12.9-1-MANJARO-ARM #1 SMP Thu Jun 3 10:11:08 UTC 2021 aarch64 GNU/Linux
maliit-keyboard 2.0.0-2

**Comment by dobey** [comment]
This behavior isn't just for Emoji, which is treated as simply another language, rather than a special function. If you have any two languages enabled, and switch to the second language in the popup menu, a single tap of the language button will switch betwen the current and previous layouts used. Having more than two layouts enabled, obviously makes this a bit more confusing.

I think the design was originally done this way, to be similar to the older iOS keyboard which was in use at the time (2011-2014 timeframe).

**Comment by Fuseteam** [comment]
this should be fixed with #91

**Comment by dobey** [comment]
> this should be fixed with #91

Not really. The behavior of the button for switching languages hasn't changed. The only thing that's changed is that Emoji is no longer treated as a language plugin, so it doesn't become one of the two layouts that get cycled. Instead it becomes a separate thing, and if you have only a single language enabled, the behavior is slightly more obvious as the languages key becomes the emoji key.

There will need to be additional change to improve the behavior when there are multiple languages enabled.

**Comment by Fuseteam** [comment]
>  The only thing that's changed is that Emoji is no longer treated as a language plugin, so it doesn't become one of the two layouts that get cycled

which is the OP's issue iiuc they refer to the emoji as "icons" if so they likely mean that if they switch from English to emoji then back to English, they have tap and hold to switch to Czech, iirc with pr 91 it should now switch between English and Czech seamlessly even if they do use the emoji layout

> Use (tap) the button/key to select the language - the language does not switch, the icons are displayed. (Hold works properly +1)
I think **emoji should be controlled separately.**

**Comment by dobey** [comment]
> which is the OP's issue iiuc they refer to the emoji as "icons" if so they likely mean that if they switch from English to emoji then back to English, they have tap and hold to switch to Czech, iirc with pr 91 it should now switch between English and Czech seamlessly even if they do use the emoji layout

Yes, but enable a third language, and notice you still only cycle through two of them with the single tap. The behavior is not intuitive and "Emoji" here was a red herring, as it shouldn't have been a language plug-in in the first place. The behavior of the button otherwise though is still not intuitive, and should be improved. Hence, I think this issue is not simply resolved by moving the emoji away from being a plug-in.

**Comment by Fuseteam** [comment]
ah true, it always cycles between the current and the previous language plug in
